// clientes/livros-angular/src/app/editora-dados/editora-dados.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { Editora } from '../model/editora';
import { ControleEditorasService } from '../contole/controle-editoras.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './editora-dados.component.html',
  styleUrls: ['./editora-dados.component.css']
})

export class EditoraDadosComponent {
  router: Router;
  editora: Editora = new Editora();
  autoresForm: string = "";
  editoras: Array<Editora>;

  constructor(router: Router,
    private servEditora: ControleEditorasService) {
    this.router = router;
    this.editoras = [];
  }

  incluir = (editora: Editora): void => {
    
    const inclusao$: Observable<boolean> = this.servEditora.incluir(editora);
    
    inclusao$.subscribe({
      next: (success: boolean) => {
        if (success) {
          console.log("Editora incluído com sucesso via Observable. Navegando...");
          this.router.navigateByUrl("/editoraLista");
        } else {
          console.log("Inclusão falhou (retornou falso).");
        }
      },
      error: (err) => {
        console.error("Erro durante a inclusão:", err);
      },
      complete: () => {
        console.log("Inclusão completa.");
      }
    });
  }
}

<main class="container mt-4">
    <div class="page-header mb-4">
        <h1>Dados da Editora</h1>
    </div>

    <form (submit)="incluir(editora)">
        <div class="form-group">
            <label for="editora">Código:</label>
            <input type="text" class="form-control" name="codEditora" [(ngModel)]="editora.codEditora"><br />
        </div>
        <label for="nome">Nome:</label>
        <input type="text" class="form-control" name="nome" [(ngModel)]="editora.nome"><br />
        <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>

</main>

// clientes/livros-next/app/pages/EditoraDados/page.tsx
'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import ControleEditoras from '../../controle/ControleEditoras'; 
import Editora from '../../model/Editora'; 

const controleEditoras = new ControleEditoras();

export default function EditoraDados() {
    const navigate = useRouter(); 

    const [codEditora, setCodEditora] = useState('');
    const [nome, setNome] = useState('');
    
    const incluir = (event: React.FormEvent) => {
        event.preventDefault();

        const novaEditora = new Editora(
            "", 
            Number(codEditora), 
            nome 
        );

        controleEditoras.incluir(novaEditora)
            .then(() => {
                navigate.push('../pages/EditoraLista');
            })
            .catch(error => console.error("Erro ao incluir editora:", error));
    };

    return (
        <main className="container mt-4">
            <h1>Inclusão de Editora</h1>
            <form onSubmit={incluir}>
                <div className="mb-3">
                    <label htmlFor="codEditora" className="form-label">Código</label>
                    <input type="text" className="form-control" id="codEditora" value={codEditora} onChange={(e) => setCodEditora(e.target.value)} required />
                </div>

                <div className="mb-3">
                    <label htmlFor="nome" className="form-label">Nome</label>
                    <input type="text" className="form-control" id="nome" value={nome} onChange={(e) => setNome(e.target.value)} required />
                </div>

                <button type="submit" className="btn btn-primary">Incluir Editora</button>
            </form>
        </main>
    );
}
