// clientes/livros-react/src/LivroDados.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import ControleEditoras from './controle/ControleEditoras';
import ControleLivros from './controle/ControleLivros';
import Livro from './model/Livro';

const controleEditora = new ControleEditoras();
const controleLivro = new ControleLivros();

export default function LivroDados() {
    const navigate = useNavigate();

    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [codEditora, setCodEditora] = useState(0);
    const [editoras, setEditoras] = useState([])
    const [autores, setAutores] = useState('');

    useEffect(() => {
        controleEditora.obterEditoras()
            .then(listaEditoras => {
                setEditoras(listaEditoras);
                if (listaEditoras.length > 0) {
                    setCodEditora(listaEditoras[0].codEditora);
                }
            })
            .catch(error => console.error("Erro ao obter editoras:", error));
    }, []);

    const incluir = (event) => {
        event.preventDefault();
        
        const codEditoraNumber = Number(codEditora);
        
        const novoLivro = new Livro(
            "",
            codEditoraNumber,
            titulo,
            resumo,
            autores.split('\n').map(autor => autor.trim()).filter(Boolean)
        );

        controleLivro.incluir(novoLivro)
            .then(() => {
                navigate('/');
            })
            .catch(error => console.error("Erro ao incluir livro:", error));
    };

    return (
        <main className="container mt-4">
            <h1>Inclusão de Livro</h1>
            <form onSubmit={incluir}>
                <div className="mb-3">
                    <label htmlFor="titulo" className="form-label">Título</label>
                    <input type="text" className="form-control" id="titulo" value={titulo} onChange={(e) => setTitulo(e.target.value)} required />
                </div>

                <div className="mb-3">
                    <label htmlFor="resumo" className="form-label">Resumo</label>
                    <textarea className="form-control" id="resumo" rows={3} value={resumo} onChange={(e) => setResumo(e.target.value)} required></textarea>
                </div>

                <div className="mb-3">
                    <label htmlFor="codEditora" className="form-label">Editora</label>
                    <select
                        className="form-select"
                        id="codEditora"
                        value={codEditora}
                        onChange={(e) => setCodEditora(e.target.value)}
                        required
                    >
                        {editoras.map((editora) => (
                            <option key={editora.codEditora} value={editora.codEditora}>
                                {editora.nome}
                            </option>
                        ))}
                    </select>
                </div>

                <div className="mb-3">
                    <label htmlFor="autores" className="form-label">Autores (um por linha)</label>
                    <textarea className="form-control" id="autores" rows={3} value={autores} onChange={(e) => setAutores(e.target.value)} required></textarea>
                </div>

                <button type="submit" className="btn btn-primary">Incluir Livro</button>
            </form>
        </main>
    );
}

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { Editora } from '../model/editora';
import { Livro } from '../model/livro';
import { ControleEditorasService } from '../contole/controle-editoras.service';
import { ControleLivrosService } from '../contole/controle-livros.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})

export class LivroDadosComponent {
  router: Router;
  livro: Livro = new Livro();
  autoresForm: string = "";
  editoras: Array<Editora>;

  constructor(router: Router,
    private servEditora: ControleEditorasService,
    private servLivros: ControleLivrosService) {
    this.router = router;
    this.editoras = [];
  }

  ngOnInit(): void {
    this.servEditora.getEditoras().subscribe(data => {
      this.editoras = data;
    });
  }

  incluir = (livro: Livro): void => {
    livro.autores = this.autoresForm.split('\n');
    
    const inclusao$: Observable<boolean> = this.servLivros.incluir(livro);
    
    inclusao$.subscribe({
      next: (success: boolean) => {
        if (success) {
          console.log("Livro incluído com sucesso via Observable. Navegando...");
          this.router.navigateByUrl("/livroLista");
        } else {
          console.log("Inclusão falhou (retornou falso).");
        }
      },
      error: (err) => {
        console.error("Erro durante a inclusão:", err);
      },
      complete: () => {
        console.log("Inclusão completa.");
      }
    });
  }
}

<main class="container mt-4">
    <div class="page-header mb-4">
        <h1>Dados do Livro</h1>
    </div>

    <form (submit)="incluir(livro)">
        <div class="form-group">
            <label for="livro">Título:</label>
            <input type="text" class="form-control" name="titulo" [(ngModel)]="livro.titulo"><br />
        </div>
        <label for="resumo">Resumo:</label>
        <input type="text" class="form-control" name="resumo" [(ngModel)]="livro.resumo"><br />
        <label for="editora">Editora:</label>
        <select id="meuSelect" class="form-control custom-select dropdown-toggle" [(ngModel)]="livro.codEditora"
            [ngModelOptions]="{standalone: true}">
            <option *ngFor="let editora of editoras" [value]="editora.codEditora">
                {{ editora.nome }}
            </option>
        </select><br />
        <label for="autores">Autores (1 por linha):</label>
        <textarea class="form-control" name="autores" [(ngModel)]="autoresForm" rows="3"></textarea><br />
        <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>

</main>
